export { default as airportRoutes } from "./airports"
export { default as authRoutes } from "./auth"
export { default as flightRoutes } from "./flight"
export { default as ticketsRoutes } from "./ticket"
export { default as luggageRoutes } from "./luggage"
export { default as flightClassRoutes } from "./flightClass"